Repository dscigdtuw/kickstart_to_github-Hacktoberfest2020, pull requests merged in 2020-10, with the labels that each got.

#2 Create dummy.md
  profiles/dummy.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#4 Nandini
  CONTRIBUTOR/nandini.md
  profiles/Nandini_Saini.md
  scripts/nandini-412.js
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#3 create muskaan.md
  CONTRIBUTOR/muskaan.md
  profiles/muskaan.md
  scripts/hello_muskaanv0.java
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#5 Create wireless.md
  profiles/wireless.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#7 Create helloworld.java
  scripts/helloworld.java
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#9 Update helloworld.java
  scripts/helloworld.java
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#10 Kotlin Language
  CONTRIBUTOR/pahlevi.md
  profiles/pahlevikun.md
  scripts/hello_pahlevikun.kt
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#11 [add] my profile and tower of hanoi implementation in c++
  code_in_hacktober/tower_of_hanoi.cpp
  profiles/anjalbam.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#15 Adding Hello World in JavaScript
  CONTRIBUTOR/PoojaGera.md
  profiles/PoojaGera.md
  scripts/hello_pooja-gera.js
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#14 hello_harsh.cpp
  scripts/hello_harsh.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#13 Harsh_pandey.md
  profiles/Harsh_pandey.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#12 harsh.md
  CONTRIBUTOR/Harsh.md
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#37 Create Parikshit
  CONTRIBUTOR/Parikshit
Labels: hacktoberfest-accepted

#36 Files added
  CONTRIBUTOR/Balpreet.md
  profiles/Balpreet_Kaur.md
  scripts/hello_balpreetkaur291.cpp
Labels: hacktoberfest-accepted

#35 Create binary search.cpp
  scripts/binary search.cpp
Labels: hacktoberfest-accepted

#27 Mitali
  CONTRIBUTOR/mitali.md
  profiles/Mitali_Jain.md
  scripts/hello_mitali.js
Labels: hacktoberfest-accepted

#28 Aditi
  CONTRIBUTOR/Aditi__Agrawal.md
  profiles/Aditi_Agrawal.md
  scripts/hello_world_aditibindal27.java
Labels: hacktoberfest-accepted

#29 Create SaumyaJangid.md
  CONTRIBUTOR/SaumyaJangid.md
Labels: hacktoberfest-accepted

#34 Create HELLO WORLD.CPP
  scripts/HELLO WORLD.CPP
Labels: hacktoberfest-accepted

#30 Create SaumyaJangid.md
  profiles/SaumyaJangid.md
Labels: hacktober-accepted

#31 Create hello_SaumyaJangid.cpp
  scripts/hello_SaumyaJangid.cpp
Labels: hacktober-accepted

#32 gcd.cpp
  code_in_hacktober/gcd.cpp
Labels: hacktoberfest-accepted

#38 Create nivedita.md
  CONTRIBUTOR/nivedita.md
Labels: hacktober-accepted, hacktoberfest-accepted

#42 Even_Odd.cpp
  Even_Odd.cpp
Labels: hacktoberfest-accepted

#39 HelloWorld.cpp
  HelloWorld.cpp
Labels: hacktoberfest-accepted

#40 Fibonacci.cpp
  Fibonacci.cpp
Labels: hacktoberfest-accepted

#41 Factorial.cpp
  Factorial.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#45 fibonacci.cpp
  fibonacci.cpp
Labels: hacktoberfest-accepted

#43 create helloworlds-rafaelamicaela
  scripts/helloworld-rafaela.py
Labels: hacktoberfest-accepted
